language: java
jdk:
  - openjdk8
after_success:
  - curl -L https://github.com/codegeny/codegeny-keys/raw/master/secured.tar.gz | openssl enc -d -aes-256-cbc -pass pass:$PASSPHRASE | tar xz -C ~
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy --settings $HOME/settings.xml -DskipTests=true -B"
