name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn verify --batch-mode --update-snapshots
      - name: Deploy to Sonatype Nexus
        run: |
          echo -n "$SECRET_KEY_RING" | gpg --import > ./gpg.logs
          echo -n "$MAVEN_SETTINGS" > ./settings.xml
          mvn deploy --settings ./settings.xml --batch-mode --update-snapshots -DskipTests=true
        env:
          SECRET_KEY_RING: ${{secrets.SECRET_KEY_RING}}
          MAVEN_SETTINGS: ${{secrets.MAVEN_SETTINGS}}
